package be.e1.bssv.util.J569801.proxy;

/**
 * Generated class, do not edit.
 *
 * This stub class was generated by weblogic
 * webservice stub gen on Wed Dec 05 12:57:58 EST 2012 
 */

public class ProcessFTPFiles_Stub 
     extends weblogic.wsee.jaxrpc.StubImpl
     implements be.e1.bssv.util.J569801.proxy.ProcessFTPFiles, /**/java.io.Serializable
{

  public ProcessFTPFiles_Stub(weblogic.wsee.wsdl.WsdlPort port, 
                        weblogic.wsee.jaxrpc.ServiceImpl service) 
    throws javax.xml.rpc.ServiceException
  {
    super(port, be.e1.bssv.util.J569801.proxy.ProcessFTPFiles.class, service);
  }
  
    
  /**
   * Operation Name : {http://xmlns.oracle.com/FTPManager/FTPManager/ProcessFTPFiles}process   */

  public be.e1.bssv.util.J569801.com.oracle.xmlns.ftpmanager.ftpmanager.ftpfilemanager.ProcessResponse process(be.e1.bssv.util.J569801.com.oracle.xmlns.ftpmanager.ftpmanager.ftpfilemanager.Process payload) throws java.rmi.RemoteException {

    java.util.ArrayList _args = new java.util.ArrayList();
    _args.add(payload);
    
    try {
            java.lang.Object _result = _invoke("process", _args.toArray());
      return (be.e1.bssv.util.J569801.com.oracle.xmlns.ftpmanager.ftpmanager.ftpfilemanager.ProcessResponse)_result;
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {

      
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
  }  public void processAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.util.J569801.com.oracle.xmlns.ftpmanager.ftpmanager.ftpfilemanager.Process payload) throws java.rmi.RemoteException  {
    java.util.ArrayList _args = new java.util.ArrayList();

    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY, "true");
    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY, apc);
    _setProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY, "process");
    _setProperty(weblogic.wsee.async.AsyncConstants.OPERATION_NAME_PROPERTY,
                 "process");
    _setProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY, "be.e1.bssv.util.J569801.com.oracle.xmlns.ftpmanager.ftpmanager.ftpfilemanager.ProcessResponse");
    _args.add(payload);
    
    try {
      java.lang.Object _result = _invoke("process", _args.toArray());
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
    finally {
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY);

    }
  }
   
    
  private Object writeReplace() throws java.io.ObjectStreamException {
    java.util.HashMap map = new java.util.HashMap();
            map.put("ProcessFTPFiles_pt", "ProcessFTPFiles_Pt");
            
    return new weblogic.wsee.tools.clientgen.stubgen.StubSerialWrapper(
      "be.e1.bssv.util.J569801.proxy.Processftpfiles_Client_Ep",
      (String)map.get(_getPortName()),
      _getUserProperties());
  }
}