package be.e1.bssv.util.J569801.proxy;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Wed Dec 05 12:57:58 EST 2012  
 */

public interface ProcessFTPFiles extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://xmlns.oracle.com/FTPManager/FTPManager/ProcessFTPFiles}process   */

  public be.e1.bssv.util.J569801.com.oracle.xmlns.ftpmanager.ftpmanager.ftpfilemanager.ProcessResponse process(be.e1.bssv.util.J569801.com.oracle.xmlns.ftpmanager.ftpmanager.ftpfilemanager.Process payload) throws java.rmi.RemoteException;
    public void processAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.util.J569801.com.oracle.xmlns.ftpmanager.ftpmanager.ftpfilemanager.Process payload) throws java.rmi.RemoteException ;
  
}