package be.e1.bssv.util.J569801.proxy;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Wed Dec 05 12:57:58 EST 2012  
 */

public interface Processftpfiles_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: ProcessFTPFiles_Pt  
     // Port Type: ProcessFTPFiles   
     //***********************************
     
  /**
   * returns ProcessFTPFiles_Pt port in this service 
   */
  be.e1.bssv.util.J569801.proxy.ProcessFTPFiles getProcessFTPFiles_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getProcessFTPFiles_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.util.J569801.proxy.ProcessFTPFiles getProcessFTPFiles_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.util.J569801.proxy.ProcessFTPFiles getProcessFTPFiles_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.util.J569801.proxy.ProcessFTPFiles getProcessFTPFiles_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.util.J569801.proxy.ProcessFTPFiles getProcessFTPFiles_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569801.proxy.ProcessFTPFiles getProcessFTPFiles_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569801.proxy.ProcessFTPFiles getProcessFTPFiles_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569801.proxy.ProcessFTPFiles getProcessFTPFiles_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569801.proxy.ProcessFTPFiles getProcessFTPFiles_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }