<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="MediaObjectNotification" targetNamespace="http://xmlns.oracle.com/MediaObjectsManager/MediaObjectsManager/MediaObjectNotification" xmlns="" xmlns:client="http://xmlns.oracle.com/MediaObjectsManager/MediaObjectsManager/MediaObjectNotification" xmlns:ns1="http://www.beav.com/e1/mediaobjectnotify" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:documentation>
        http://FMWDVVHN1:8001/soa-infra/services/BSP/MediaObjectsManager!1.0/MediaObjectNotification.wsdl
    </wsdl:documentation>
  <plnk:partnerLinkType name="MediaObjectNotification">
    <plnk:role name="MediaObjectNotificationProvider" portType="client:MediaObjectNotification"/>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:client="http://xmlns.oracle.com/MediaObjectsManager/MediaObjectsManager/MediaObjectNotification" xmlns:ns1="http://www.beav.com/e1/mediaobjectnotify" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
      <import namespace="http://www.beav.com/e1/mediaobjectnotify" schemaLocation="MediaObjectNotify.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="MediaObjectNotificationRequestMessage">
    <wsdl:part element="ns1:MediaObjectNotifyRequest" name="payload"/>
  </wsdl:message>
  <wsdl:message name="MediaObjectNotificationResponseMessage">
    <wsdl:part element="ns1:MediaObjectNotifyResponce" name="payload"/>
  </wsdl:message>
  <wsdl:portType name="MediaObjectNotification">
    <wsdl:operation name="process">
      <wsdl:input message="client:MediaObjectNotificationRequestMessage"/>
      <wsdl:output message="client:MediaObjectNotificationResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MediaObjectNotificationBinding" type="client:MediaObjectNotification">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="process">
      <soap:operation soapAction="process" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="mediaobjectnotification_client_ep">
    <wsdl:port binding="client:MediaObjectNotificationBinding" name="MediaObjectNotification_pt">
      <soap:address location="http://FMWDVVHN1:8001/soa-infra/services/BSP/MediaObjectsManager/mediaobjectnotification_client_ep"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>