package be.e1.bssv.util.J569804.proxy;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Fri Feb 08 14:07:13 EST 2013  
 */

public interface Mediaobjectnotification_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: MediaObjectNotification_Pt  
     // Port Type: MediaObjectNotification   
     //***********************************
     
  /**
   * returns MediaObjectNotification_Pt port in this service 
   */
  be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getMediaObjectNotification_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }