package be.e1.bssv.util.J569804.proxy;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Fri Feb 08 14:07:13 EST 2013 */

public class Mediaobjectnotification_Client_Ep_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements be.e1.bssv.util.J569804.proxy.Mediaobjectnotification_Client_Ep {

  public Mediaobjectnotification_Client_Ep_Impl() throws javax.xml.rpc.ServiceException {
    this("be/e1/bssv/util/J569804/proxy/Mediaobjectnotification_Client_Ep_saved_wsdl.wsdl", null);
  }
  
  public Mediaobjectnotification_Client_Ep_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public Mediaobjectnotification_Client_Ep_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://xmlns.oracle.com/MediaObjectsManager/MediaObjectsManager/MediaObjectNotification", "mediaobjectnotification_client_ep"),
          "be/e1/bssv/util/J569804/proxy/Mediaobjectnotification_Client_Ep_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: MediaObjectNotification_Pt 
  // Port Type: MediaObjectNotification 
  //***********************************

  be.e1.bssv.util.J569804.proxy.MediaObjectNotification mvar_MediaObjectNotification_Pt;

  /**
   * returns MediaObjectNotification_Pt port in this service 
   */
  public be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_MediaObjectNotification_Pt == null) {
      mvar_MediaObjectNotification_Pt =
        new be.e1.bssv.util.J569804.proxy.MediaObjectNotification_Stub(_getPort("MediaObjectNotification_pt"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_MediaObjectNotification_Pt)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_MediaObjectNotification_Pt;
  }

  /**
   * @Deprecated  Use getMediaObjectNotification_Pt(byte[] username, byte[] password)
   */
  public be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getMediaObjectNotification_Pt();
  }

  public be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getMediaObjectNotification_Pt();
  }
  
      public be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(
    java.io.InputStream policyInputStream) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("MediaObjectNotification_pt", policyInputStream, true, true);
    return getMediaObjectNotification_Pt();
  }

  public be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(
    java.io.InputStream policyInputStream, 
    boolean inbound, 
    boolean outbound) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("MediaObjectNotification_pt", policyInputStream, inbound, outbound);
    return getMediaObjectNotification_Pt();
  }
 
  public be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("MediaObjectNotification_pt", null, inboundPolicies, outboundPolicies);
    return getMediaObjectNotification_Pt();
  }
  
  public be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("MediaObjectNotification_pt", null, inboundPolicies, outboundPolicies);
    return getMediaObjectNotification_Pt();
  }
  
  public be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(
    String operationName,
    java.io.InputStream[] inboundPolicies, 
    java.io.InputStream[] outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("MediaObjectNotification_pt", operationName, inboundPolicies, outboundPolicies);
    return getMediaObjectNotification_Pt();
  }
  
  public be.e1.bssv.util.J569804.proxy.MediaObjectNotification getMediaObjectNotification_Pt(
    String operationName,
    java.util.Set<java.io.InputStream> inboundPolicies, 
    java.util.Set<java.io.InputStream> outboundPolicies) 
    throws javax.xml.rpc.ServiceException
  {
    _loadPolicy("MediaObjectNotification_pt", operationName, inboundPolicies, outboundPolicies);
    return getMediaObjectNotification_Pt();
  }
    
}