package be.e1.bssv.util.J569804.proxy;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Fri Feb 08 14:07:13 EST 2013  
 */

public interface MediaObjectNotification extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://xmlns.oracle.com/MediaObjectsManager/MediaObjectsManager/MediaObjectNotification}process   */

  public be.e1.bssv.util.J569804.com.beav.e1.mediaobjectnotify.MediaObjectNotifyResponce process(be.e1.bssv.util.J569804.com.beav.e1.mediaobjectnotify.MediaObjectNotifyRequest payload) throws java.rmi.RemoteException;
    public void processAsync(weblogic.wsee.async.AsyncPreCallContext apc, be.e1.bssv.util.J569804.com.beav.e1.mediaobjectnotify.MediaObjectNotifyRequest payload) throws java.rmi.RemoteException ;
  
}