package be.e1.bssv.J560201.proxy;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Mon Nov 05 16:22:30 EST 2012  
 */

public interface Processapprovalgateway_Client_Ep extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: ProcessApprovalGateway_Pt  
     // Port Type: ProcessApprovalGateway   
     //***********************************
     
  /**
   * returns ProcessApprovalGateway_Pt port in this service 
   */
  be.e1.bssv.J560201.proxy.ProcessApprovalGateway getProcessApprovalGateway_Pt() throws javax.xml.rpc.ServiceException;

  /**
   * @Deprecated Use getProcessApprovalGateway_Pt(byte[] username, byte[] password);
   */
  be.e1.bssv.J560201.proxy.ProcessApprovalGateway getProcessApprovalGateway_Pt(String username, String password) throws javax.xml.rpc.ServiceException;

  be.e1.bssv.J560201.proxy.ProcessApprovalGateway getProcessApprovalGateway_Pt(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
      be.e1.bssv.J560201.proxy.ProcessApprovalGateway getProcessApprovalGateway_Pt(java.io.InputStream policyInputStream) throws javax.xml.rpc.ServiceException;  
  be.e1.bssv.J560201.proxy.ProcessApprovalGateway getProcessApprovalGateway_Pt(java.io.InputStream policyInputStream, boolean inbound, boolean outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J560201.proxy.ProcessApprovalGateway getProcessApprovalGateway_Pt(String operationName, 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J560201.proxy.ProcessApprovalGateway getProcessApprovalGateway_Pt(String operationName,
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J560201.proxy.ProcessApprovalGateway getProcessApprovalGateway_Pt( 
    java.util.Set<java.io.InputStream> inbound, java.util.Set<java.io.InputStream> outbound) throws javax.xml.rpc.ServiceException;
  be.e1.bssv.J560201.proxy.ProcessApprovalGateway getProcessApprovalGateway_Pt(
    java.io.InputStream[] inbound, java.io.InputStream[] outbound) throws javax.xml.rpc.ServiceException;
       
  }